repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.11
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0  # Use the ref you want to point at
  hooks:
  - id: check-merge-conflict
  - id: check-toml
  # - id: check-yaml

- repo: local
  hooks:
  - id: MkDocsbuild
    name: Building the markdown documentation with `mkdocs build`
    entry: bash -c 'mkdocs build'
    language: system

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.6
  hooks:
  - id: clang-format
    args: [--style=LLVM]

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.12.1
  hooks:
  - id: markdownlint-cli2
    args: [--fix]
