# A note for mkdocs:
# See <https://realpython.com/python-project-documentation-with-mkdocs/>
#  and <https://www.mkdocs.org/user-guide/deploying-your-docs/>
# `mkdocs serve`: It creates a test documentation and makes it available at localhost. All the changes made to the documentation are propagated instantly to assist the development.
# `mkdocs build`: It build the complete static documentation pages along with html files and static assets. Committing it to the repo ensures that the self contained documentation pages are packaged with the package. However, it is not enough to host the documentation on github.
# `mkdocs gh-deploy`: GitHub repositories automatically serve static content when committed to a branch named `gh-pages`. The command `mkdocs gh-deploy` just does that by rebuilding the documentation from markdown files and docstrings, then commits them to the `gh-pages` branch and pushes it to the `gh-pages` branch on remote. Be aware that you will not be able to review the built site before it is pushed to GitHub. Therefore, you may want to verify any changes you make to the docs beforehand by using the `build` or `serve` commands and reviewing the built files locally. **If there are untracked files or uncommitted work in the local repository where mkdocs gh-deploy is run, these will be included in the pages that are deployed.**

# So follow the following workflow:
# 1. Make changes to the repository. Review any changes to documentation with `mkdocs serve`.
# 2. Build the documentation with `mkdocs build`. --->>> I have now added a pre-commit hook for it, so no need to run it explicitly. Now simply run `pre-commit run --all-files` for testing.
# 3. Commit the changes and new documentation.
# 4. Run `mkdocs gh-deploy` to deploy the documentation to github. --->>> I have deployed a github workflow to initiate `mkdocs gh-deploy` whenever a commit is pushed on the `main` branch on github. See <.github/workflow/documentation.yaml>


site_name: BrahMap Documentation
site_url: https://anand-avinash.github.io/BrahMap/

site_author: Avinash Anand, Giuseppe Puglisi
site_description: >-
  BrahMap: A scalable and modular map-making framework for the CMB experiments

# Repository
repo_name: anand-avinash/BrahMap
repo_url: https://github.com/anand-avinash/BrahMap
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024-present | Avinash Anand, Giuseppe Puglisi

theme:
  name: "material"
  font:
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.view # view source of this page
    - content.action.edit # edit source of this page, related to `edit_uri`
    - content.code.copy
    - content.code.select
    - search.suggest # search suggestion
    - search.highlight # highlight the search terms
    - navigation.top
    - navigation.tabs
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.top # Back to top button
    - toc.follow
    # - navigation.sections
    # - navigation.tracking # to track the address of the page with the active anchor
    # - header.autohide
  palette:
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/link
    #     name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


markdown_extensions:
  ### Matjax support
  - pymdownx.arithmatex:
      generic: true
  ### Code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  ### TOC permalink
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

### Matjax support
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  ### Enable docstring parsing
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            allow_inspection: true  # import the modules and inspect them
            # force_inspection: true  # Force import (see if it works for extensions)
            show_signature: true  # show function signature
            show_signature_annotations: true  # show signature annotation
            inherited_members: false
            # summary: true
            show_docstring_raises: false
  - search # Enable search

### Page tree
nav:
  - Overview:
    - index.md
    - Installation: overview/installation.md
    - Roadmap: overview/roadmap.md
    - License: overview/license.md
    - What is in the name?: overview/name.md
  
  - Quick Start: 
    - quick_start/index.md
  
  - User Guide:
    - user_guide/index.md
  
  - API Reference:
    - api_reference/index.md

      
    - litebird_sim Interface:
      - api_reference/lbsim/index.md
      - LBSimProcessTimeSamples: api_reference/lbsim/LBSimProcessTimeSamples.md      
      - LBSim_InvNoiseCovLO_UnCorr: api_reference/lbsim/LBSim_InvNoiseCovLO_UnCorr.md
      - LBSim_InvNoiseCovLO_Circulant: api_reference/lbsim/LBSim_InvNoiseCovLO_Circulant.md
      - LBSim_InvNoiseCovLO_Toeplitz: api_reference/lbsim/LBSim_InvNoiseCovLO_Toeplitz.md
      - LBSimGLSParameters: api_reference/lbsim/LBSimGLSParameters.md
      - LBSim_compute_GLS_maps: api_reference/lbsim/LBSim_compute_GLS_maps.md
      - LBSimGLSResult: api_reference/lbsim/LBSimGLSResult.md     

    - Core Map-making Interface:
      - api_reference/core/index.md
      - SolverType: api_reference/core/SolverType.md
      - ProcessTimeSamples: api_reference/core/ProcessTimeSamples.md
      - PointingLO: api_reference/core/PointingLO.md
      - BlockDiagonalPreconditionerLO: api_reference/core/BlockDiagonalPreconditionerLO.md
      - NoiseCovLO_Diagonal: api_reference/core/NoiseCovLO_Diagonal.md
      - NoiseCovLO_Circulant: api_reference/core/NoiseCovLO_Circulant.md
      - NoiseCovLO_Toeplitz01: api_reference/core/NoiseCovLO_Toeplitz01.md
      - BlockDiagNoiseCovLO: api_reference/core/BlockDiagNoiseCovLO.md
      - InvNoiseCovLO_Diagonal: api_reference/core/InvNoiseCovLO_Diagonal.md
      - InvNoiseCovLO_Circulant: api_reference/core/InvNoiseCovLO_Circulant.md
      - InvNoiseCovLO_Toeplitz01: api_reference/core/InvNoiseCovLO_Toeplitz01.md
      - BlockDiagInvNoiseCovLO: api_reference/core/BlockDiagInvNoiseCovLO.md
      - GLSParameters: api_reference/core/GLSParameters.md
      - compute_GLS_maps_from_PTS: api_reference/core/compute_GLS_maps_from_PTS.md
      - compute_GLS_maps: api_reference/core/compute_GLS_maps.md
      - separate_map_vectors: api_reference/core/separate_map_vectors.md
      - GLSResult: api_reference/core/GLSResult.md 
    
    - Math Functions:
      - api_reference/math_functions/index.md
      - parallel_norm: api_reference/math_functions/parallel_norm.md
      - cg: api_reference/math_functions/cg.md

    - Utilities:
      - api_reference/utilities/index.md
      - bash_colors: api_reference/utilities/bash_colors.md
      - modify_numpy_context: api_reference/utilities/modify_numpy_context.md
      - plot_LinearOperator: api_reference/utilities/plot_LinearOperator.md
    
    - Base Operators:
      - api_reference/base_operators/index.md
      - BaseLinearOperator: api_reference/base_operators/BaseLinearOperator.md
      - LinearOperator: api_reference/base_operators/LinearOperator.md
      - IdentityOperator: api_reference/base_operators/IdentityOperator.md
      - DiagonalOperator: api_reference/base_operators/DiagonalOperator.md
      - MatrixLinearOperator: api_reference/base_operators/MatrixLinearOperator.md
      - ZeroOperator: api_reference/base_operators/ZeroOperator.md
      - InverseLO: api_reference/base_operators/InverseLO.md
      - ReducedLinearOperator: api_reference/base_operators/ReducedLinearOperator.md
      - SymmetricallyReducedLinearOperator: api_reference/base_operators/SymmetricallyReducedLinearOperator.md
      - aslinearoperator: api_reference/base_operators/aslinearoperator.md
      - BlockLinearOperator: api_reference/base_operators/BlockLinearOperator.md
      - BlockDiagonalLinearOperator: api_reference/base_operators/BlockDiagonalLinearOperator.md
      - BlockHorizontalLinearOperator: api_reference/base_operators/BlockHorizontalLinearOperator.md
      - BlockVerticalLinearOperator: api_reference/base_operators/BlockVerticalLinearOperator.md

    - Miscellaneous: 
      - api_reference/misc/index.md
      - TypeChangeWarning: api_reference/misc/TypeChangeWarning.md
      - LowerTypeCastWarning: api_reference/misc/LowerTypeCastWarning.md
      - filter_warnings: api_reference/misc/filter_warnings.md
      - ShapeError: api_reference/misc/ShapeError.md
  
  - Development:
    - development/index.md
  
  - Changelog:
    - changelog/index.md
