[tool.poetry]
name = "brahmap"
version = "0.1.0"
description = ""
authors = ["Avinash Anand <36325275+anand-avinash@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
